
browser:
  type: chromium  
  headless: true  
  timeout: 30000   
  ignore_https_errors: true
  viewport:
    width: 1920
    height: 1080
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  max_concurrency: 4
  
  proxy:
    enabled: false
    server: "http://127.0.0.1:8080"
    username: ""
    password: ""
  
  headers:
    X-Forwarded-For: "127.0.0.1"
    
credentials:
  user_dict: "data/username.txt"  
  pass_dict: "data/password.txt"  
  universal_passwords:  
    - "' or '1'='1"
    - "admin'--"
    - "' or 1=1 --"
  common_combinations:  
    - ["admin", "admin"]
    - ["admin", "123456"]
    - ["root", "root"]
  
captcha:
  enabled: true
  
  api:
    type: "local"  
    key: ""
    url: ""
    timeout: 30000
  
  local:
    model_path: "data/ocr_model"
    preprocess: true  
path_finder:
  dict_path: "data/paths.txt"  
  methods: ["GET"]  
  timeout: 5000     
  threads: 10       
  status_codes:     
    - 200
    - 302
    - 401
    - 403

fingerprint:
  db_path: "data/fingerprints.json"  

logging:
  level: "INFO"  
  file: "logs/authscope.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_size: 10485760  
  backup_count: 5

reporting:
  save_screenshots: true
  screenshot_path: "reports/screenshots"
  html_report: true
  csv_report: true
  output_dir: "reports"